### ISSUE TITLE
I can't get the program to start.

### ISSUE THREAD

**Issue by davipbl** [Grashjs/frontend#20]
**Describe the bug**
I can't seem to run the program

**To Reproduce**
I cloned the repo, run the commands in  usage, tried updating and got an error.

PS C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend> npm start

> grash@0.1.0 start
> react-scripts start --max_old_space_size=6096

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
(node:23604) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:23604) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

TypeError: Cannot set property mark of #<Object> which has only a getter
TypeError: Cannot set property mark of #<Object> which has only a getter
    at Object.connectTypeScriptPerformance (C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\typescript-reporter\profile\TypeScriptPerformance.js:12:36)
    at createTypeScriptReporter (C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\typescript-reporter\reporter\TypeScriptReporter.js:40:49)
    at Object.<anonymous> (C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:21:30)
    at Generator.next (<anonymous>)
    at C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:4:12)
    at C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:19:88
    at Object.<anonymous> (C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\rpc\RpcService.js:23:38)
    at Generator.next (<anonymous>)
TypeError: Cannot set property mark of #<Object> which has only a getter
TypeError: Cannot set property mark of #<Object> which has only a getter
    at Object.connectTypeScriptPerformance (C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\typescript-reporter\profile\TypeScriptPerformance.js:12:36)
    at createTypeScriptReporter (C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\typescript-reporter\reporter\TypeScriptReporter.js:40:49)
    at Object.<anonymous> (C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:21:30)
    at Generator.next (<anonymous>)
    at C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:4:12)
    at C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:19:88
    at Object.<anonymous> (C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\node_modules\fork-ts-checker-webpack-plugin\lib\rpc\RpcService.js:23:38)
    at Generator.next (<anonymous>)
Failed to compile.

Module not found: Error: Can't resolve 'src/mocks' in 'C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\src'
ERROR in ./src/index.tsx 5:0-19
Module not found: Error: Can't resolve 'src/mocks' in 'C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\src'

ERROR in ./src/index.tsx 8:0-47
Module not found: Error: Can't resolve 'src/hooks/useScrollTop' in 'C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\src'

ERROR in ./src/index.tsx 11:0-30
Module not found: Error: Can't resolve 'src/store' in 'C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\src'

ERROR in ./src/index.tsx 12:0-26
Module not found: Error: Can't resolve 'src/App' in 'C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\src'

ERROR in ./src/index.tsx 13:0-62
Module not found: Error: Can't resolve 'src/contexts/SidebarContext' in 'C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\src'

ERROR in ./src/index.tsx 14:0-58
Module not found: Error: Can't resolve 'src/contexts/TitleContext' in 'C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\src'

ERROR in ./src/index.tsx 15:0-51
Module not found: Error: Can't resolve 'src/serviceWorker' in 'C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\src'

ERROR in ./src/index.tsx 16:0-78
Module not found: Error: Can't resolve 'src/contexts/CompanySettingsContext' in 'C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\src'

ERROR in ./src/index.tsx 17:0-59
Module not found: Error: Can't resolve 'src/contexts/JWTAuthContext' in 'C:\Users\davip\OneDrive\Documentos\Projetos_Programação\frontend\src'

ERROR in src\index.tsx
  Line 17:1:  ReactDOM.render is deprecated since React 18.0.0, use createRoot instead, see https://reactjs.org/link/switch-to-createroot  react/no-deprecated

Search for the keywords to learn more about each error.

webpack compiled with 10 errors

Here is my error list

**Comment by iib0011** [comment]
What did you update? You should be able to start without changing anything in the code

**Comment by davipbl** [comment]
Well, I'm using VSCode and Windows Terminal, when I first cloned the repository and followed all the commands in the usage section, the terminal output suggested me to run 'npm audit fix', which I did. When I used npm start, it didn't work at first, I had to change my node version (currently at v19 and changed to v16.2) and it output the error message I submited

**Comment by davipbl** [comment]
I changed my node_modules folder and it seemed like the server went up, but nothing loaded. 
![image](https://github.com/Grashjs/frontend/assets/73298622/49087687-19fc-46e1-a597-9e38f8184b37)
Here is an image of what happens when I try to use 'npm audit fix'.

**Comment by davipbl** [comment]
It compiled successfully after loading for awhile!

Maybe with the updates something might have changed, but I was able to compile it successfully after waiting some time!

**Comment by davipbl** [comment]
Now I guess I am having issues with logging in, can't seem to create an account or find a way to login

**Comment by iib0011** [comment]
Either use the live api at [https://api.atlascmms.com](https://api.atlascmms.com) or [run the api locally](https://github.com/Grashjs/api)
